# This is a basic workflow that is manually triggered

name: PITest

on: 
  push:
    branches:
      - master
      - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pitest:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    defaults:
      run:
        working-directory: ./player
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests
      run: mvn test -P pitest
    
    - name: Checkout
      uses: actions/checkout@v1
    - run: |
        zip -r pit-reports.zip target/pit-reports
        ls -l
    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@1.0.5
      with:
        token: xoxb-744038435863-3253611990165-l65US4wKUdXKcVfLVPHHPTI8
        path: pit-reports.zip
        channel: si3-qgl-21-22-les_gorilles_bronzes
