# This is a basic workflow that is manually triggered

name: PITest

on: 
  push:
    branches:
      - master
      - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pitest:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    defaults:
      run:
        working-directory: ./player
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests
      run: mvn test -P pitest
    - name: Send email
      uses: dawidd6/action-send-mail@v3.6.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        subject: Github Actions PITtest result
        to: thomaspaul987@gmail.com
        from: Thomas Paul
        attachments: ./target/pit-reports/*
      
